# Generated by Django 4.1.2 on 2022-10-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=120)),
                ('client_phone_number', models.CharField(max_length=12)),
                ('task_brief', models.CharField(max_length=240)),
                ('logo', models.BooleanField()),
                ('presentation', models.BooleanField()),
                ('social_networks', models.BooleanField()),
                ('identity', models.BooleanField()),
                ('infographics', models.BooleanField()),
                ('offline_adds', models.BooleanField()),
                ('task_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at')),
                ('task_accomplishment', models.BooleanField(default=False)),
            ],
        ),
    ]
